title: blank
first_name: Michael
middle_name: null
last_name: Bleher
email: mbleher@mathi.uni-heidelberg.de
description: 'personal website

  '
footer_text: '<i> Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted
  by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>. </i>

  '
keywords: mathematical physics, physical mathematics, topological data analysis, computational
  topology, geometric machine learning
lang: en
icon: favicon.png
url: https://subthaumic.github.io
baseurl: null
last_updated: true
impressum_path: /impressum/
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: false
  theme_light: flat
  theme_dark: gitdimmed
rss_icon: false
navbar_fixed: true
footer_fixed: false
max_width: 880px
serve_og_meta: false
serve_schema_org: false
og_image: null
github_username: subthaumic
x_username: subthaumic
mastodon_username: mathstodon.xyz/@subthaumic
bluesky: subthaumic.bsky.social
scholar_userid: PchAbTkAAAAJ
orcid_id: 0000-0002-7796-1665
arxiv_id: bleher_m_1
gitlab_username: null
semanticscholar_id: null
whatsapp_number: null
linkedin_username: null
telegram_username: null
medium_username: null
quora_username: null
publons_id: null
lattes_id: null
osf_id: null
research_gate_profile: null
scopus_id: null
blogger_url: null
work_url: null
keybase_username: null
wikidata_id: null
wikipedia_id: null
dblp_url: null
stackoverflow_id: null
kaggle_id: null
lastfm_id: null
spotify_id: null
pinterest_id: null
unsplash_id: null
instagram_id: null
facebook_id: null
youtube_id: null
discord_id: null
zotero_username: null
wechat_qr: null
contact_note: null
google_analytics: null
cronitor_analytics: null
google_site_verification: null
bing_site_verification: null
blog_name: null
blog_description: null
permalink: null
pagination:
  enabled: false
related_blog_posts:
  enabled: false
  max_related: 1
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  talks:
    output: true
    permalink: /talks/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
  events:
    output: true
    permalink: /events/:path/
announcements:
  enabled: true
  scrollable: false
  limit: 5
latest_posts:
  enabled: true
  scrollable: true
  limit: 3
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
- _pages
exclude:
- bin
- Gemfile
- Gemfile.lock
- vendor
keep_files:
- CNAME
- .nojekyll
- .git
plugins:
- jekyll-archives
- jekyll-email-protect
- jekyll-feed
- jekyll-get-json
- jekyll-imagemagick
- jekyll-jupyter-notebook
- jekyll-link-attributes
- jekyll-minifier
- jekyll-paginate-v2
- jekyll/scholar
- jekyll-sitemap
- jekyll-toc
- jekyll-twitter-plugin
- jemoji
defaults:
- scope:
    path: assets
  values:
    sitemap: false
sass:
  style: compressed
jekyll-minifier:
  exclude:
  - robots.txt
  uglifier_args:
    harmony: true
jekyll-archives:
  enabled:
  - year
  - tags
  - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: /blog/:year/
    tag: /blog/tag/:name/
    category: /blog/category/:name/
display_tags: null
display_categories: null
scholar:
  last_name:
  - Bleher
  first_name:
  - Michael
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: publications.bib
  bibliography_template: bib
  bibtex_filters:
  - latex
  - smallcaps
  - superscript
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: '@*'
  group_by: year
  group_order: descending
enable_publication_badges:
  altmetric: false
  dimensions: false
filtered_bibtex_keywords:
- abbr
- abstract
- arxiv
- bibtex_show
- html
- pdf
- selected
- supp
- blog
- code
- poster
- video
- slides
- website
- preview
- altmetric
max_author_limit: 3
more_authors_animation_delay: 5
enable_publication_thumbnails: true
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude: null
imagemagick:
  enabled: true
  widths:
  - 480
  - 800
  - 1400
  input_directories:
  - assets/img/
  input_formats:
  - .jpg
  - .jpeg
  - .png
  - .tiff
  - .gif
  output_formats:
    webp: -quality 85
enable_google_analytics: false
enable_cronitor_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: true
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
bootstrap-table:
  version: 1.22.1
jquery:
  version: 3.6.0
  integrity: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
mathjax:
  version: 3.2.0
masonry:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.20.0
  integrity:
    css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
    js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
medium_zoom:
  version: 1.0.8
  integrity: sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8=
jekyll_get_json:
- data: resume
  json: assets/json/resume.json
jsonresume:
- basics
- work
- education
- languages
navbar:
- title: Events
  url: /events/
toc:
  enable: true
  side: left
